USE CLC
GO

CREATE TABLE scratch.L_CESAM_Import_CambiCollocatore_DatiAFB
(
	IdImport INT
	,num_op INT
	,n_op_externa BIGINT
	,t_ope varchar(10)
	,type_ varchar(10)
	,contratto_afb varchar(50)
	,intestatario1 varchar(250)
	,intestatario2 varchar(250)
	,intestatario3 varchar(250)
	,intestatario4 varchar(250)
	,DataInserimentoFlusso DATETIME
	,ISIN VARCHAR(50)
	,DescrizioneProdotto VARCHAR(100)
	,Quote DECIMAL(3)
	,SIP VARChAR(5)
	,Collocatore VARCHAR(100)
	,DataInvioSTF DATETIME
	,Stato VARCHAR(50)
	,DataConclusione DATETIME
	,Urgenze VARCHAR(5)

	--CONSTRAINT PK_CESAM_Import_CambiCollocatore_DatiAFB_ID PRIMARY KEY (ID)
	
)


CREATE TABLE scratch.L_CESAM_Import_CambiCollocatore_DatiFEND
(
	IdImport INT,
	SOC VARCHAR(5)
	,PRODOTTO VARCHAR(5)
	,ISIN VARCHAR(50)
	,MANDATO VARCHAR(20)
	,QUOTE DECIMAL(3)
	,CTV DECIMAL(2)
	,DATA DATETIME
	,DOSSIER VARCHAR(20)
	,CLIENTI_INTESTATARIO VARCHAR(9)
	,COGNOME_INTESTATARIO VARCHAR(100)
	,NOME_INTESTATARIO VARCHAR(100)
	,CLIENTE_COINTESTATARIO_1 VARCHAR(9)
	,COGNOME_COINTESTATARIO_1 VARCHAR(100)
	,NOME_COINTESTATARIO_1    VARCHAR(100)
	,CLIENTE_COINTESTATARIO_2 VARCHAR(9)
	,COGNOME_COINTESTATARIO_2 VARCHAR(100)
	,NOME_COINTESTATARIO_2    VARCHAR(100)
	,CLIENTE_COINTESTATARIO_3 VARCHAR(9)
	,COGNOME_COINTESTATARIO_3 VARCHAR(100)
	,NOME_COINTESTATARIO_3    VARCHAR(100)
	,CLIENTE_COINTESTATARIO_4 VARCHAR(9)
	,COGNOME_COINTESTATARIO_4 VARCHAR(100)
	,NOME_COINTESTATARIO_4    VARCHAR(100)
	,CLIENTE_COINTESTATARIO_5 VARCHAR(9)
	,COGNOME_COINTESTATARIO_5 VARCHAR(100)
	,NOME_COINTESTATARIO_5    VARCHAR(100)
	,CF VARCHAR(5)
	,COGNOME_CF VARCHAR(100)
	,NOME_CF VARCHAR(100)
	,COLLOCATORE_USCENTE VARCHAR(100)
	,EXTERNAL_CODE VARCHAR(50)

	--CONSTRAINT PK_tbl_name_ID PRIMARY KEY (ID)
)

GO




